
spring:
  data:
    maria:
      jdbc-url: jdbc:mariadb://lgcns-project.cozuxbklbor4.us-east-2.rds.amazonaws.com:3306/test?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: team1
      password: 1q2w3e4r!
  jpa:
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true
